[package]
name = "zodiatic-bindings-test"
version = "0.1.0"
authors = ["Kenneth Lee <kennethlee@ud.hk>"]
edition = "2021"

[dependencies]
itertools = "0.10"
zodiatic-bindings = { version = "0.1.0", path = "../bindings" }
cosmwasm-std = "1.0.0"
schemars = "0.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
cw-multi-test = "0.14.0"
cw-storage-plus = "0.14.0"
anyhow = "1"
thiserror = "1.0.21"
